In [83]:
# Numpyを使って多次元配列オブジェクトを作成する
import numpy as np
# 1次元配列を作成する
a = np.array([1, 2, 3])
print(a)
# 2次元配列を作成する
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
# 3次元配列を作成する
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


In [85]:
# ndaarayオブジェクトの形状を確認する
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 3)
